### ISSUE TITLE
What do the proportions represent in babynames?

### ISSUE THREAD

**Issue by AmeliaMN** [hadley/babynames#12]
I'm playing with the data and wondering why 

```
totals <- babynames %>%
   group_by(year) %>%
   summarize(totprop = sum(prop), tot=sum(n))
```

doesn't return what I was expecting. I know `tot` in my summarized data should be less than `n_all` in the `applicants` data because uncommon names aren't represented in `babynames`, but why doesn't `totprop` add up to something less than or equal to 1? Most `totprop`s are about 1.8.

**Comment by garrettgman** [comment]
@AmeliaMN I'm almost certain that the proportions are calculated within gender (e.g., proportion of boys, proportion of girls). So your `totprop` would approach 2 if the data set had complete coverage.

**Comment by AmeliaMN** [comment]
Thanks for confirming. That was my guess but wanted a second opinion before I submitted a PR.

**Comment by AmeliaMN** [comment]
Hah, looks like I actually went ahead and submitted the PR in August!
