### ISSUE TITLE
Add sex to births data

### ISSUE THREAD

**Issue by garrettgman** [hadley/babynames#18]
The current `births` data set only contains the *total* number of children by year. I'm finding it nearly impossible to do anything useful with it.

If we break the `births` data out by sex and year, we can do all of the examples we used to do in Stat 405. If you'd like the `births` data set we used in Stat 405, let me know. I still have it.

**Comment by hadley** [comment]
I'd include it if I could find it :(

But standardising against applicants is probably just as reasonable
