### ISSUE TITLE
Typo in GitHub repo description: An R package "contain" all baby names data from the SSA

### ISSUE THREAD

**Issue by sfirke** [hadley/babynames#21]
Should be "containing".  Don't think I can submit a PR for this.  Sorry for the triviality 😀

**Comment by russellpierce** [comment]
When I search the current version of the package it looks like the plural form "contains" is used throughout.  Do you still see this error?

**Comment by sfirke** [comment]
See here: ![image](https://user-images.githubusercontent.com/7569808/48846350-ee982780-ed6c-11e8-9b8c-42bb95cca417.png)

It's in the repo description itself, not any code file, thus why I can't write a PR for it (I don't think).

**Comment by hadley** [comment]
Fixed, thanks!
