### ISSUE TITLE
update with 2016 data

### ISSUE THREAD

**Issue by sfirke** [hadley/babynames#22]
Easily updated:
**applicants**: can run applicants.R as is
**names**: can run names.R as is after running applicants.R

Less so:
**births**: I don't have .xls file to run the script.  Manually-obtained total for 2016 is 3945875 ([p.2](https://www.cdc.gov/nchs/data/nvsr/nvsr67/nvsr67_01.pdf))
**lifetables**: script lifetables.R does not work, this URL is now broken: "http://www.ssa.gov/oact/NOTES/as120/LifeTables_Tbl_7_%s.html

Given that there's already a manual data entry element to births, it might be worth hardcoding the births data in the package already into births.R and eliminating reference to the .xls source except as a comment.

I will submit a PR for names (probably the most used part of this package) and applicants.

**Comment by hadley** [comment]
Fixed by #30
