### ISSUE TITLE
Feature request: compute rank within sex/year and provide in babynames data.frame

### ISSUE THREAD

**Issue by sfirke** [hadley/babynames#24]
Rank is the most common way that baby name popularity is discussed.  In 2016 "Jaxon" for a boy had n = 8054, prop = 0.00401, rank = 51.  For the typical person, knowing it's the 51st most popular boy name may be more digestible than the other measures.

Rank is displayed on mouseover here: http://www.babynamewizard.com/voyager

**Comment by sfirke** [comment]
This would be a great first PR for someone.

**Comment by hadley** [comment]
I think this was a deliberate choice because computing the rank is a perfect motivation for learning grouped mutate. I'd be hesitant to add it now without careful thinking through where I've used the data.
