### ISSUE TITLE
Update with 2017 Data

### ISSUE THREAD

**Issue by russellpierce** [hadley/babynames#25]
@hadley It looks like the PR for the 2016 data didn't catch your attention.  Would one for 2017? :)  

Related... I found an XLS by the same name as the one you note went missing from the census website in two locations...

http://webapp1.dlib.indiana.edu/virtual_disk_library/index.cgi/4232284/FID3473/Sprdshts/MINI-HS/02HS0013.xls and https://www2.census.gov/library/publications/2004/compendia/statab/123ed/hist/02HS0013.xls

The only difference appears to be that births in {babynames} appears to be rounded/truncated at the 1000s place whereas my source documents have a more detailed count.

**Comment by hadley** [comment]
Yes, although looking at that PR makes me realise we need some regression tests or similar to make sure that the data import works correctly. Maybe start with a PR that adds some regression tests using `expect_known_output()` to save a couple of tabulations (e.g. births per sex/year)?

**Comment by russellpierce** [comment]
Re: validity/regression tests, please consider: https://github.com/hadley/babynames/pull/27 as a first rough draft.

**Comment by russellpierce** [comment]
#27 Has been merged.  Now working on updating the datasets.
