### ISSUE TITLE
Release babynames 1.0.0

### ISSUE THREAD

**Issue by hadley** [hadley/babynames#31]
Submit to CRAN: 
 
* [x] `usethis::use_version('1.0.0')` 
* [x] `devtools::check_win_devel()` (again!) 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] `usethis::use_release_tag()` 
* [x] `usethis::use_dev_version()` 
* [ ] Finish blog post 
* [ ] Tweet 
* [ ] Add link to blog post in pkgdown news menu

**Comment by hadley** [comment]
@russellpierce this is the checklist - I think if you comment, I can copy and paste it in so that you can edit it — if you work on the "prepare for release" I can do the rest.

**Comment by russellpierce** [comment]
This is a comment so that you can copy and paste it in. :)

**Comment by russellpierce** [comment]
```
── R CMD check results ────────────────────────────────── babynames 0.3.0.9000 ────
Duration: 21.5s

❯ checking installed package size ... NOTE
    installed size is 10.1Mb
    sub-directories of 1Mb or more:
      data  10.0Mb

0 errors ✔ | 0 warnings ✔ | 1 note ✖
```

There will be a [minor PR](https://github.com/russellpierce/babynames/tree/release_tweaks_1_0_0) to clean up an roxygen warning.  I'm holding that back until I've gotten closer to finishing the checklist.

**Comment by russellpierce** [comment]
Passed `devtooos::check_win_devel()`
```
Version contains large components (0.3.0.9000)
...
* DONE
Status: 1 NOTE
```

**Comment by hadley** [comment]
FWIW the blog post can be pretty short, but it'd be nice to remind people of this package, and maybe point out the alternatives now available for other countries?

**Comment by russellpierce** [comment]
The project didn't previously use pkgdown and this will be my first time using it.  My check mark there may need extra 👀 when the time comes.  All I did was execute usethis::use_pkgdown(), pkgdown::build_site(), and manually change 'All functions' to read 'All datasets'.

**Comment by hadley** [comment]
Oh, I'll need to set up the automated pkgdown building, so just check in `_pkgdown.yml` and I'll do the rest

**Comment by hadley** [comment]
@russellpierce do you have a twitter account?

**Comment by russellpierce** [comment]
Yes, it is RussellSPierce.  I got a bit hung up with the pkgdown step. I'll see if I can get back to it soon.

**Comment by hadley** [comment]
I think it's easiest for me to set that up (since it requires some fiddling with travis). Once that's done (hopefully in <15 minutes), I'll tweet out a delayed announcement
